/**
 * 301 redirect map: legacy WordPress URLs → new equivalents (Handover §11).
 * Category pages point into the faceted Products search; info pages to content pages.
 * Sources are written without a trailing slash (Next normalises trailing slashes).
 *
 * v2.1: the faceted catalogue moved from /ranges to /products (/ranges is now the range-family
 * browse). Product slugs were also collapsed from per-size to per-colour — PRODUCT_REDIRECTS maps
 * the old size-suffixed slugs onto the new colour slugs (generated by migrate:colours).
 */

// Legacy facet category slug → faceted-search query (now on /products).
const FACET_REDIRECTS = {
  // Effects
  'wood-effect-ranges': 'effect=wood',
  'stone-effect-ranges': 'effect=stone',
  'marble-effect-ranges': 'effect=marble',
  'concrete-ranges': 'effect=concrete',
  'slate-effect-ranges': 'effect=slate',
  'metallic-effect-ranges': 'effect=metallic',
  'patterned-textured-ranges': 'effect=patterned',
  'topcer-victorian-tiles': 'effect=victorian',
  // Colours
  'black-nero-ebano': 'colour=black',
  'charcoal-antracite': 'colour=charcoal',
  'grigio-gris-grey': 'colour=grey',
  'blanco-white-perla': 'colour=white',
  'marfil-cream-light-beige': 'colour=cream',
  'caramel-tan-dark-beige': 'colour=beige',
  'walnut-taupe-brown': 'colour=brown',
  'pink-rose': 'colour=pink',
  'red-cherry-wood-terracotta': 'colour=red',
  'orange-coral': 'colour=orange',
  'golden-oak-yellow': 'colour=yellow',
  'green-mint-sage': 'colour=green',
  'teal-turquoise': 'colour=teal',
  'light-blue': 'colour=light-blue',
  'blue-navy': 'colour=blue',
  'plum-mauve-purple': 'colour=purple',
  'multi-coloured': 'colour=multi',
  'copper-tiles': 'colour=copper',
  'golden-tiles': 'colour=gold',
  'Silver-Tiles': 'colour=silver',
  'iron-steel-other-metallic-tiles': 'colour=iron',
  'oxidised-metallic-tiles': 'colour=oxidised',
  // Finishes
  'natural-finish-tiles': 'finish=natural',
  'lappato-finish-tiles': 'finish=lappato',
  'polished-gloss-finish-tiles': 'finish=gloss',
  'anti-slip-finish-tiles': 'finish=anti-slip',
  // Edges
  'pressed-edged-tiles': 'edge=pressed',
  'rectified-edged-tiles': 'edge=rectified',
  'chiselled-edged-tiles': 'edge=chiselled',
  // Formats
  'hexagonal-tiles': 'format=hexagonal',
  'brick-effect-tiles': 'format=brick-effect',
  'brick-slips': 'format=brick-slips',
  'pre-boxed-modular-porcelain-tiles': 'format=pre-boxed-modular',
  miscellaneous: 'format=miscellaneous',
  // Uses
  'porcelain-tiles': 'material=porcelain',
  'wall-tiles': 'application=wall',
  'mosaic-pieces': 'application=mosaic',
  'special-pieces': 'application=special-pieces',
  'outdoor-porcelain': 'application=outdoor',
}

// Legacy slugs that map to the unfiltered catalogue search (now /products).
const TO_PRODUCTS = [
  'all-ranges',
  'new-ranges',
  'clearance-tiles',
  'tile-viewer',
  'kitchen-tiles',
  'floral-prints',
  'terrazzo-prints',
  'travertine-prints',
  'weathered-tiles',
  'vintage-tiles',
  'encaustic-tiles',
  'rustic-tiles',
  'fitting-materials-accessories',
]

// Legacy bathroom slugs → the bathrooms page.
const TO_BATHROOMS = [
  'bathroom-tiles',
  'bathroom-clearance-items',
  'phoenix-bathrooms',
  'sonas-bathrooms',
]

// Legacy size category pages (enumerated from /tile-viewer/). The faceted search has no
// exact-dimension facet (size = sizeBand), so these map to the page's category facet — relevant
// and never an empty exact-size result. Slugs are <WxH>[x20]-mm-<category>-tiles.
const SIZE_SLUGS = [
  '1000x1000-mm-porcelain-tiles',
  '100x600-mm-porcelain-tiles',
  '100x600-mm-wood-effect-tiles',
  '100x700-mm-wood-effect-tiles',
  '1200x1200x20-mm-outdoor-tiles',
  '150x1200-mm-wood-effect-tiles',
  '150x300-mm-porcelain-tiles',
  '150x800-mm-wood-effect-tiles',
  '150x900-mm-wood-effect-tiles',
  '200x1200-mm-wood-effect-tiles',
  '200x200-mm-porcelain-tiles',
  '200x200-mm-wall-tiles',
  '200x600-mm-wall-tiles',
  '200x800-mm-wood-effect-tiles',
  '240x880-mm-wood-effect-tiles',
  '250x1500-mm-wood-effect-tiles',
  '250x250-mm-porcelain-tiles',
  '250x400-mm-wall-tiles',
  '250x500-mm-wall-tiles',
  '250x750-mm-wall-tiles',
  '265x1800-mm-wood-effect-tiles',
  '300x1200-mm-porcelain-tiles',
  '300x1200-mm-wood-effect-tiles',
  '300x1200x20-mm-outdoor-tiles',
  '300x300-mm-porcelain-tiles',
  '300x600-mm-porcelain-tiles',
  '300x600-mm-wall-tiles',
  '300x600x20-mm-outdoor-tiles',
  '300x900-mm-wall-tiles',
  '310x980-mm-wall-tiles',
  '315x1000-mm-wall-tiles',
  '320x625-mm-wall-tiles',
  '333x550-mm-wall-tiles',
  '333x800-mm-wall-tiles',
  '400x1200-mm-wall-tiles',
  '450x1200-mm-wall-tiles',
  '450x450-mm-porcelain-tiles',
  '450x900-mm-porcelain-tiles',
  '450x900-mm-wall-tiles',
  '450x900x20-mm-outdoor-tiles',
  '500x500-mm-porcelain-tiles',
  '600x1200-mm-porcelain-tiles',
  '600x1200-mm-wall-tiles',
  '600x1200-mm-wood-effect-tiles',
  '600x1200x20-mm-outdoor-tiles',
  '600x600-mm-porcelain-tiles',
  '600x600-mm-wood-effect-tiles',
  '600x600x20-mm-outdoor-tiles',
  '600x900-mm-porcelain-tiles',
  '600x900x20-mm-outdoor-tiles',
  '650x1500-mm-porcelain-tiles',
  '750x1500-mm-porcelain-tiles',
  '750x750-mm-porcelain-tiles',
  '800x1600-mm-porcelain-tiles',
  '800x800-mm-porcelain-tiles',
  '800x800-mm-wood-effect-tiles',
  '800x800x20-mm-outdoor-tiles',
  '900x900-mm-porcelain-tiles',
  '900x900x20-mm-outdoor-tiles',
]

const SIZE_SUFFIX_FACET = {
  'porcelain-tiles': 'material=porcelain',
  'wall-tiles': 'application=wall',
  'wood-effect-tiles': 'effect=wood',
  'outdoor-tiles': 'application=outdoor',
}

// Legacy info pages → content pages.
const CONTENT_REDIRECTS = {
  'about-us': '/about',
  'about-our-suppliers': '/about',
  'tile-laying-patterns': '/about',
  'descriptive-symbols': '/about',
  'delivery-terms-conditions': '/about',
  'terms-and-conditions': '/about',
  'customer-testimonials': '/about',
  'commercial-area': '/projects',
  'customer-projects': '/projects',
}

// Old per-size product slugs → new per-colour product slugs (v2.1 colour migration).
const PRODUCT_REDIRECTS = {
  'aurora-wood-honed-300x600': 'aurora-wood-honed',
  'aurora-wood-natural-300x600': 'aurora-wood-natural',
  'yuko-blanco-600x600': 'yuko-blanco',
  'yuko-beige-600x600': 'yuko-beige',
  'woodsy-blonde-200x1200': 'woodsy-blonde',
  'trust-white-nat-600x600': 'trust-white-nat',
  'trust-silver-nat-600x600': 'trust-silver-nat',
  'trust-silver-nat-300x600': 'trust-silver-nat',
  'trust-grey-nat-600x600': 'trust-grey-nat',
  'trust-grey-strip-300x600': 'trust-grey-strip',
  'trust-beige-nat-600x600': 'trust-beige-nat',
  'toddy-natural-450x450': 'toddy-natural',
  'toddy-blanco-450x450': 'toddy-blanco',
  'timeless-grey-500x1000': 'timeless-grey',
  'tercio-terrazo-grigio-600x1198': 'tercio-terrazo-grigio',
  'tercio-terrazo-beige-600x1198': 'tercio-terrazo-beige',
  'tercio-blanco-600x1198': 'tercio-blanco',
  'tempra-smoke-600x600': 'tempra-smoke',
  'tempra-smoke-300x600': 'tempra-smoke',
  'tempra-canyon-smoke-300x600': 'tempra-canyon-smoke',
  'tempra-canyon-gris-300x600': 'tempra-canyon-gris',
  'tempra-gris-600x600': 'tempra-gris',
  'tempra-gris-300x600': 'tempra-gris',
  'tempra-carpet-2-600x600': 'tempra-carpet-2',
  'tempra-carpet-1-300x600': 'tempra-carpet-1',
  'tempra-antracite-600x600': 'tempra-antracite',
  'r11-black-structured-300x300': 'r11-black-structured',
  'prior-wood-nogal-195x1200': 'prior-wood-nogal',
  'photon-perla-600x600': 'photon-perla',
  'photon-musk-600x600': 'photon-musk',
  'palara-bone-natural-600x1200': 'palara-bone-natural',
  'nordic-white-600x600': 'nordic-white',
  'nantera-nature-600x1200': 'nantera-nature',
  'montera-light-600x900': 'montera-light',
  'metropolis-pearl-600x600': 'metropolis-pearl',
  'metropolis-gris-600x600': 'metropolis-gris',
  'metropolis-blanco-600x600': 'metropolis-blanco',
  'megane-rovere-200x1200': 'megane-rovere',
  'medovio-menfi-600x900': 'medovio-menfi',
  'medovio-dor-600x900': 'medovio-dor',
  'medovio-ernice-600x900': 'medovio-ernice',
  'medovio-decor-b-black-600x900': 'medovio-d-cor-b-black',
  'medovio-decor-b-black-200x200': 'medovio-d-cor-b-black',
  'medovio-decor-a-blue-200x200': 'medovio-d-cor-a-blue',
  'medovio-byblos-600x900': 'medovio-byblos',
  'makobi-white-333x650': 'makobi-white',
  'makobi-nature-333x650': 'makobi-nature',
  'makobi-dark-333x650': 'makobi-dark',
  'makobi-beige-333x650': 'makobi-beige',
  'lucentum-arena-600x600': 'lucentum-arena',
  'lucentum-blanco-600x600': 'lucentum-blanco',
  'legacy-noce-chiaro-plank-200x1200': 'legacy-noce-chiaro-plank',
  'legacy-noce-chiaro-inlay-900x900': 'legacy-noce-chiaro-inlay',
  'lava-murreto-300x600': 'lava-murreto',
  'lava-grey-600x600': 'lava-grey',
  'lava-cinder-600x600': 'lava-cinder',
  'lava-cinder-300x600': 'lava-cinder',
  'lantica-florac-600x900': 'lantica-florac',
  'lantica-portes-600x900': 'lantica-portes',
  'lakea-white-600x600': 'lakea-white',
  'lance-sand-600x600': 'lance-sand',
  'lance-ivory-600x600': 'lance-ivory',
  'lance-grey-600x600': 'lance-grey',
  'lance-cinder-600x600': 'lance-cinder',
  'lakea-sand-600x600': 'lakea-sand',
  'lakea-sand-300x600': 'lakea-sand',
  'lakea-sand-decor-new-300x600': 'lakea-sand-d-cor-new',
  'lakea-grey-decor-300x600': 'lakea-grey-d-cor',
  'lakea-grey-600x600': 'lakea-grey',
  'lakea-grey-300x600': 'lakea-grey',
  'indicta-multi-600x600': 'indicta-multi',
  'indicta-beige-600x600': 'indicta-beige',
  'icon-silver-mix-200x200': 'icon-silver-mix',
  'grunge-white-600x600': 'grunge-white',
  'grunge-beige-600x600': 'grunge-beige',
  'garrison-marfil-natural-800x800': 'garrison-marfil-natural',
  'fantasia-paradise-600x1200': 'fantasia-paradise',
  'fantasia-glamora-600x1200': 'fantasia-glamora',
  'cortona-avorio-honed-600x900': 'cortona-avorio-honed',
  'clubland-white-450x450': 'clubland-white',
  'clubland-ivory-450x450': 'clubland-ivory',
  'clubland-grey-450x450': 'clubland-grey',
  'borage-natural-594x594': 'borage-natural',
  'borage-greige-600x1200': 'borage-greige',
  'bolshoi-01-negro-200x200': 'bolshoi-01-negro',
  'bloka-white-800x800': 'bloka-white',
  'bloka-grey-800x800': 'bloka-grey',
  'bloka-beige-800x800': 'bloka-beige',
  'blackwater-slate-300x600': 'blackwater-slate',
  'blackwater-slate-600x600': 'blackwater-slate',
  'berwyn-alerce-natural-85x600': 'berwyn-alerce-natural',
  'berwyn-roble-natural-85x600': 'berwyn-roble-natural',
  'balti-white-500x500': 'balti-white',
  'balti-grey-500x500': 'balti-grey',
}

/** @returns {Promise<import('next').Redirect[]>} */
export function legacyRedirects() {
  const redirects = []
  for (const [slug, query] of Object.entries(FACET_REDIRECTS)) {
    redirects.push({ source: `/${slug}`, destination: `/products?${query}`, permanent: true })
  }
  for (const slug of TO_PRODUCTS) {
    redirects.push({ source: `/${slug}`, destination: '/products', permanent: true })
  }
  for (const slug of TO_BATHROOMS) {
    redirects.push({ source: `/${slug}`, destination: '/bathrooms', permanent: true })
  }
  for (const slug of SIZE_SLUGS) {
    const suffix = slug.match(/-mm-(.+)$/)?.[1] ?? ''
    const facet = SIZE_SUFFIX_FACET[suffix]
    redirects.push({
      source: `/${slug}`,
      destination: facet ? `/products?${facet}` : '/products',
      permanent: true,
    })
  }
  for (const [slug, dest] of Object.entries(CONTENT_REDIRECTS)) {
    redirects.push({ source: `/${slug}`, destination: dest, permanent: true })
  }
  for (const [oldSlug, newSlug] of Object.entries(PRODUCT_REDIRECTS)) {
    redirects.push({
      source: `/product/${oldSlug}`,
      destination: `/product/${newSlug}`,
      permanent: true,
    })
  }
  return redirects
}
