/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited.
// Regenerated by Next.js. Committed so `tsc --noEmit` works before the first build.
